name: rest
description: Rest API methods
version: 0.0.8
publish_to: none
homepage: https://github.com/RagehAz/rest.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4

  filers:
    git:
      url: https://github.com/RagehAz/filers.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
